# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: My example book
author: Carlos H. Brandt

only_build_toc_files: true

execute:
  execute_notebooks: cache
  cache: .jupyter_cache/

